# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

t1 = 0
t2 = 1
s = 0
while t1 + t2 < 4000000:
    n = t1 + t2
    if n % 2 == 0:
        s = s + n
    t1 = t2
    t2 = n
print(s)